# AgentX 独立部署配置
# 用户可以直接使用此文件部署 AgentX，无需克隆源码

services:
  # AgentX PostgreSQL数据库
  postgres:
    image: ankane/pgvector:latest
    container_name: agentx-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentx
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentx"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agentx-network

  # API网关 PostgreSQL数据库
  gateway-postgres:
    image: postgres:15-alpine
    container_name: api-gateway-postgres
    environment:
      - POSTGRES_DB=api_gateway
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    ports:
      - "5433:5432"
    volumes:
      - gateway-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d api_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agentx-network

  # MCP网关服务
  mcp-gateway:
    image: ghcr.io/lucky-aeon/mcp-gateway:latest
    container_name: agentx-mcp-gateway
    ports:
      - "8005:8080"
    networks:
      - agentx-network
    restart: unless-stopped

  # AgentX 主服务 (前端+后端一体化，但目前我们还没有这个镜像)
  # 临时解决方案：使用占位服务等待我们构建真正的前后端镜像
  agentx-placeholder:
    image: nginx:alpine
    container_name: agentx-placeholder
    ports:
      - "3000:80"
      - "8080:80"
      - "8081:80"
    networks:
      - agentx-network
    restart: unless-stopped
    command: |
      sh -c "
        echo '<html><body><h1>AgentX is starting...</h1><p>Please wait while services are being prepared.</p></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

volumes:
  postgres-data:
    name: agentx-postgres-data
  gateway-postgres-data:
    name: api-gateway-postgres-data

networks:
  agentx-network:
    driver: bridge
    name: agentx-network