version: "3.8"

services:
  # AgentX PostgreSQL数据库
  postgres:
    image: ankane/pgvector:latest
    container_name: agentx-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentx
    ports:
      - "5432:5432"
    volumes:
      - ./docs/sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentx"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agentx-network

  # RabbitMQ消息队列服务
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: agentx-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=zangzang
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - agentx-network
    restart: unless-stopped

  # API网关 PostgreSQL数据库
  gateway-postgres:
    image: postgres:15-alpine
    container_name: api-gateway-postgres
    environment:
      - POSTGRES_DB=api_gateway
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    ports:
      - "5433:5432"
    volumes:
      - ./API-Premium-Gateway/docs/sql:/docker-entrypoint-initdb.d:ro
      - gateway-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d api_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agentx-network

  # API网关服务  
  api-gateway:
    image: ghcr.io/lucky-aeon/api-premium-gateway:latest
    container_name: agentx-api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgres:5432/api_gateway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&stringtype=unspecified&assumeMinServerVersion=9.6&prepareThreshold=0&DateStyle=ISO
      - SPRING_DATASOURCE_USERNAME=gateway_user
      - SPRING_DATASOURCE_PASSWORD=gateway_pass
    depends_on:
      gateway-postgres:
        condition: service_healthy
    volumes:
      - ./logs/gateway:/app/logs
    networks:
      - agentx-network
    restart: unless-stopped

  # AgentX后端服务
  agentx-backend:
    image: agentx-backend:prod
    build:
      context: ./AgentX
      dockerfile: Dockerfile
    container_name: agentx-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/agentx
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MCP_GATEWAY_URL=http://mcp-gateway:8080
      - HIGH_AVAILABILITY_GATEWAY_URL=http://api-gateway:8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=zangzang
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=agentx
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mcp-gateway:
        condition: service_started
    volumes:
      - ./logs/backend:/app/logs
    networks:
      - agentx-network
    restart: unless-stopped

  # AgentX前端服务
  agentx-frontend:
    image: agentx-frontend:prod
    build:
      context: ./agentx-frontend-plus
      dockerfile: Dockerfile
    container_name: agentx-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - agentx-backend
    networks:
      - agentx-network
    restart: unless-stopped

  # MCP网关服务  
  mcp-gateway:
    image: ghcr.io/lucky-aeon/mcp-gateway:latest
    container_name: agentx-mcp-gateway
    ports:
      - "8005:8080" # 映射到主机的8082端口，避免冲突
    networks:
      - agentx-network
    restart: unless-stopped

volumes:
  postgres-data:
    name: agentx-postgres-data
  gateway-postgres-data:
    name: api-gateway-postgres-data
  rabbitmq-data:
    name: agentx-rabbitmq-data

networks:
  agentx-network:
    driver: bridge
    name: agentx-network
