# 容器环境配置 - 启用DevTools热更新
spring:
  devtools:
    restart:
      enabled: true
      # 排除容易产生冲突的类，解决ClassCastException问题
      exclude: >
        org/xhy/domain/**/constant/**,
        org/xhy/infrastructure/converter/**,
        org/xhy/domain/**/enums/**,
        org/xhy/infrastructure/entity/**,
        org/xhy/infrastructure/llm/protocol/enums/**
      # 优化容器环境的重启性能
      poll-interval: 1000
      quiet-period: 400
      additional-paths: src/main/java
    livereload:
      enabled: true
      port: 35729

# 容器环境的日志配置
logging:
  level:
    root: info
    org.xhy: debug
    org.springframework.boot.devtools: info
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

# 提示信息
info:
  environment: "容器开发环境"
  devtools: "已启用"
  note: "适用于Docker容器化开发，启用热更新提升开发效率" 