server:
  port: 8080
  servlet:
    context-path: /api
  # 添加Tomcat异步请求配置
  tomcat:
    threads:
      max: 200 # 最大工作线程数
    connection-timeout: 2000000 # 连接超时毫秒
    max-connections: 10000 # 最大连接数
    accept-count: 100 # 等待队列长度
    # 异步请求相关设置
    async-timeout: 300000 # 异步请求超时时间 5分钟

spring:
  application:
    name: AgentX
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agentx}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.xhy.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    type-handlers-package: org.xhy.infrastructure.converter
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

logging:
  level:
    root: info
    org.xhy: debug
  file:
    name: logs/agent-x.log
mail:
  smtp:
    host: ${MAIL_SMTP_HOST}
    port: ${MAIL_SMTP_PORT}
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
  verification:
    template: ${MAIL_VERIFICATION_TEMPLATE:您的验证码是:%s，有效期10分钟，请勿泄露给他人。}
    subject: ${MAIL_VERIFICATION_SUBJECT:AgentX - 邮箱验证码}
