server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: AgentX
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agent}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.xhy.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    type-handlers-package: org.xhy.infrastructure.converter
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

# LLM服务配置
llm:
  provider:
    default: ${LLM_DEFAULT_PROVIDER:siliconflow}
    providers:
      siliconflow:
        name: SiliconFlow
        api-url: ${SILICONFLOW_API_URL:https://api.siliconflow.cn/v1/chat/completions}
        api-key: ${SILICONFLOW_API_KEY:}
        model: ${SILICONFLOW_MODEL:Qwen/Qwen2.5-VL-72B-Instruct}
        timeout: ${SILICONFLOW_TIMEOUT:30000}

logging:
  level:
    root: info
    org.xhy: debug
  file:
    name: logs/agent-x.log
