server:
  port: 8080
  servlet:
    context-path: /api
  # 添加Tomcat异步请求配置
  tomcat:
    threads:
      max: 200 # 最大工作线程数
    connection-timeout: 20000 # 连接超时毫秒
    max-connections: 10000 # 最大连接数
    accept-count: 100 # 等待队列长度
    # 异步请求相关设置
    async-timeout: 300000 # 异步请求超时时间 5分钟

spring:
  application:
    name: AgentX
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agent}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.xhy.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    type-handlers-package: org.xhy.infrastructure.converter
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

embedding:
  name: OpenAI
  api-key: ${OPENAI_API_KEY:}
  api-url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
  timeout: ${OPENAI_TIMEOUT:30000}


# LLM服务配置
llm:
  provider:
    default: ${LLM_DEFAULT_PROVIDER:siliconflow}
    providers:
      siliconflow:
        name: SiliconFlow
        api-url: ${SILICONFLOW_API_URL:https://api.siliconflow.cn/v1/chat/completions}
        api-key: ${SILICONFLOW_API_KEY:}
        model: ${SILICONFLOW_MODEL:Qwen/Qwen2.5-VL-72B-Instruct}
        timeout: ${SILICONFLOW_TIMEOUT:30000}
dromara:
  x-file-storage: #文件存储配置
    default-platform: amazon-s3-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    amazon-s3: # 0.0.7 及以前的版本，配置名称是：aws-s3
      - platform: amazon-s3-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${S3_SECRET_ID}
        secret-key:  ${S3_SECRET_KEY}
        region: ?? # 与 end-point 参数至少填一个
        end-point: https://cos.ap-beijing.myqcloud.com # 与 region 参数至少填一个
        bucket-name: zang-1307996497
        domain: ?? # 访问域名，注意“/”结尾，例如：https://abc.hn-bkt.clouddn.com/
        base-path: s3/ # 基础路径


logging:
  level:
    root: info
    org.xhy: debug
  file:
    name: logs/agent-x.log
