# 本地环境配置 - 禁用DevTools避免类加载器冲突
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  # 本地环境数据库优化
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000

# 本地环境的日志配置
logging:
  level:
    root: info
    org.xhy: debug
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

# 提示信息
info:
  environment: "本地开发环境"
  devtools: "已禁用"
  note: "本地IDE开发推荐，避免类加载器冲突问题" 